### ISSUE TITLE
SOL-A Expanding Panel Toggle Buttons

### ISSUE THREAD

**Issue by RedAV8R** [ChrisAdderley/NearFutureSolar#2]
On this specific panel there are two buttons, both 'Deploy' which changes to 'Retract' when it is deployed'. And a 'Toggle' button which stays the same, and does both actions. Is that really necessary, unless the Toggle is going to be made into some sort of 'shut off' where it would disconnect that source?

**Comment by ChrisAdderley** [comment]
With https://github.com/ChrisAdderley/NearFutureSolar/commit/fcf0b4ba761aed47bb7ffc67d535a590054850a8 this toggle was relegated to where it should be, the action groups panel.
