### ISSUE TITLE
NIV-10 and NIV-30 no EC

### ISSUE THREAD

**Issue by leatherneck6017** [ChrisAdderley/NearFutureSolar#27]
Thanks for the great work on the update. Seems I've found a bug with the 2 non-deploying curved solar panels. They don't generate EC no matter how much sun shines on them! Discovered this in my modded career, double checked on a vanilla install. All other panels working as expected.

**Comment by leatherneck6017** [comment]
Oh, and looking at the configs, are the names matching up correctly? The NIV-10 has max EC of 30 and the NIV-30 is 10. Just seems like flip-flopped names is all.

**Comment by ChrisAdderley** [comment]
Can you elaborate on what the tags that are showing in the action menu?

**Comment by leatherneck6017** [comment]
Not blocked. It can say full sun exposure and have zero EC output.

**Comment by ChrisAdderley** [comment]
Also a problem with the deploying ones too.

**Comment by ChrisAdderley** [comment]
Resolved and in testing for 0.8.2
