### ISSUE TITLE
symmetry problem

### ISSUE THREAD

**Issue by 0142929** [ChrisAdderley/NearFutureSolar#30]
centers of some panels are displaced
![1](https://user-images.githubusercontent.com/896793/27957226-33122a82-6326-11e7-9fc8-47c559c3b52e.jpg)
![2](https://user-images.githubusercontent.com/896793/27957230-36ab36f2-6326-11e7-8462-180f35323f8a.jpg)

**Comment by ChrisAdderley** [comment]
Probably not worth the effort to fix right now.
