### ISSUE TITLE
static-truss-3 isn't patched to CTT

### ISSUE THREAD

**Issue by theJesuit** [ChrisAdderley/NearFutureSolar#61]
I believe that in the 
NearFutureSolar/Patches/NFSolarCommunityTechTree.cfg

there should also be the line 

@PART[nfs-panel-static-truss-3]:NEEDS[CommunityTechTree]
{
	@TechRequired = advPVMaterials
}

otherwise the static-truss-3 would stay at the electrics node.

Unless this is intentional?

Peace.

**Comment by ChrisAdderley** [comment]
Ready for next version

**Comment by ChrisAdderley** [comment]
Released.
