### ISSUE TITLE
No Energy Flow/Sun Exposure when status aligned to the sun

### ISSUE THREAD

**Issue by mytan31** [ChrisAdderley/NearFutureSolar#63]
![Annotation 2019-07-30 232643](https://user-images.githubusercontent.com/53485709/62142918-b98f9c00-b321-11e9-9357-50168c87acc7.png)

**Comment by ChrisAdderley** [comment]
I suspect your sun angle is very low and perpendicular to the panel. Try rotating your ship 90 degrees and see what happens.

**Comment by mytan31** [comment]
It appears after installing all 3 of the latest update for Kopernicus mod solve the problem. Thank you for your assistance!
https://github.com/Kopernicus/Kopernicus/releases/latest
https://github.com/Kopernicus/KittopiaTech/releases/latest
https://github.com/Kopernicus/Kopernicus-Backport/releases/tag/backport-1.6.1-9

**Comment by ChrisAdderley** [comment]
No problem!
