### ISSUE TITLE
SOL-A can't be deployed/retracted in edit mode

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFutureSolar#7]
The right click menu offers no option for it.

**Comment by ChrisAdderley** [comment]
When did Squad add this feature for stock panels? I wasn't even aware of it.

**Comment by pyalot** [comment]
No idea when it was added, I only started playing KSP since 1.0.4 and it was in there.

**Comment by ChrisAdderley** [comment]
Guess it was added sometime between 1.0 and then. I've never looked for it because I always assumed it wasn't possible without TweakableAnything or similar. Should be an easy fix though.

**Comment by ChrisAdderley** [comment]
Fixed in https://github.com/ChrisAdderley/NearFutureSolar/commit/3f4b4f9daf82f546bf391de847158d677b14136a

**Comment by toric55** [comment]
seems to have reappeared.
