### ISSUE TITLE
localization broken

### ISSUE THREAD

**Issue by redPanther** [ChrisAdderley/NearFutureSolar#72]
Hi,
thx for the superb plugin!
I realized that after last changes the localization is broken due to rename of parts. The en-us.cfg was updated, the other files not.
can you fix it?
thx again!

**Comment by ChrisAdderley** [comment]
I can't actually. The localization content changed so everything would need to be rewritten or would be incorrect. Some of the localizations have been updated by the authors, some have not. As I don't speak the languages with the exception of French, I can't adjust this. Sorry.
