### ISSUE TITLE
OKEB-15 Copernicus - point of exposure calc position

### ISSUE THREAD

**Issue by firdacz** [ChrisAdderley/NearFutureSolar#73]
As mentioned on the forum, the point of exposure calculation is not extended:
![img](https://imgup.cz/images/2020/02/17/panels.png)

The bottom panel is blocked by the battery, although it is actually not shadowed by it
(but the point where the panels were folded probably is).

KSP Forum: https://forum.kerbalspaceprogram.com/index.php?/topic/155465-18x-near-future-technologies-nfex-updates-feb-6th/&do=findComment&comment=3742606

**Comment by ChrisAdderley** [comment]
Addressed in the dev branch, will be part of 1.2.0

**Comment by firdacz** [comment]
fixed, thank you
