### ISSUE TITLE
CKAN v1.2.3 - HTTP Response 404

### ISSUE THREAD

**Issue by benpoulson** [ChrisAdderley/NearFutureSolar#82]
Currently getting a 404 when trying to download the latest version (v1.2.3) via CKAN or directly from spacedock.info (https://spacedock.info/mod/559/Near%20Future%20Solar)

**Comment by benpoulson** [comment]
Update: this looks to also be happening on several NearFuture mods.

Error downloading NearFutureConstruction 1.2.3: The remote server returned an error: (404) Not Found.
Error downloading NearFutureLaunchVehicles 2.0.3: The remote server returned an error: (404) Not Found.
Error downloading NearFutureSolar 1.2.3: The remote server returned an error: (404) Not Found.
Error downloading NearFutureSpacecraft 1.3.3: The remote server returned an error: (404) Not Found.

**Comment by ChrisAdderley** [comment]
I can't download anything from Spacedock at all, seems like they're having a problem. Unfortunately I can't do anything about that. Download from one of the alternate links.

**Comment by benpoulson** [comment]
Looks to have been resolved now. Followed the progress on their discord. 👌
