### ISSUE TITLE
NearFutureSolar and tweakscale

### ISSUE THREAD

**Issue by RealKolago** [ChrisAdderley/NearFutureSolar#9]
Is there a way to make NearFutureSolar compatible with tweakscale?

**Comment by ChrisAdderley** [comment]
You should ask the TweakScale guys about this, I don't support TweakScale myself.

**Comment by RealKolago** [comment]
Please take a look here:
http://github.com/pellinor0/TweakScale/issues/6

"I had a look in https://github.com/ChrisAdderley/NearFutureSolar/blob/master/ModuleCurvedSolarPanel.cs

The problem seems to be that TotalEnergyRate is used only once to calculate chargePerTransform, probably this is done before TweakScale tries to scale it. chargePerTransform can not be scaled because it is not a kspField.

In my opinion this is best solved in NF-Solar, by evaluating TotalEnergyRate directly in the fixedUpdate method.

EDIT: I am working on a pull request for NF-Solar"

**Comment by ChrisAdderley** [comment]
Will look at verifying this for next version.

**Comment by ChrisAdderley** [comment]
Finally fixed in the next version
